### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by hugows** [martincohen/Hale#1]
Hi martin,

I downloaded QtCreator today to try to build Hale. I couldn't compile the dependency oniguruma, due to missing headers, it seems (eg "regparse.h"). Do you have any tips? Should I go looking at the Twitch streams do find out how to configure it?

Cheers!

**Comment by martincohen** [comment]
I will be making a non-Qt build with only a single .bat file. So only thing you will need is Windows SDK and MSVC compiler. But I can't focus on that right now, I will try hard to make that ready sometime around the end of the marathon (sunday / monday).

**Comment by martincohen** [comment]
Hello Hugo, I just found a weird thing in my commits. I haven't commited any .h or .hpp files. Not sure what happened, maybe my brain shut off at one point. :) However, give it a try now, it should work.
